package ru.example.appForCalculatingNetLoad.dataStructurs.Calculator.netLoadCalculator.section;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Consumers {
    FLATS_WITH_ELECTRIC_STOVE_10_kW("Квартиры (с эл.плит.) 10 кВт",
            "кВт/шт",
            10,
            0.98),
    FLATS_WITH_ELECTRIC_STOVE_10_kW_WITH_AIR_CONDITIONERS("Квартиры (с эл.плит.) 10 кВт, с кондиционерами",
            "кВт/шт",
            10,
            0.93),
    FLATS_WITH_ELECTRIC_STOVE_MORE_THAN_10_kW("Квартиры (с эл.плит.) более 10 кВт",
            "кВт/шт",
            11,
            0.98),
    FLATS_WITH_ELECTRIC_STOVE_MORE_THAN_10_kW_WITH_AIR_CONDITIONERS("Квартиры (с эл.плит.) более 10 кВт, с кондиционерами",
            "кВт/шт",
            11,
            0.93),
    FLATS_WITH_ELECTRIC_STOVE_LESS_THAN_10_kW("Квартиры (с эл.плит.) менее 10 кВт",
            "кВт/шт",
            9,
            0.98),
    FLATS_WITH_ELECTRIC_STOVE_LESS_THAN_10_kW_WITH_AIR_CONDITIONERS("Квартиры (с эл.плит.) менее 10 кВт, с кондиционерами",
            "кВт/шт",
            9,
            0.93),
    SS_PANEL("Щит СС",
            "кВт/шт",
            3,
            0.95),
    SOCKET_NETWORKS("Розеточные сети",
            "кВт/корпус",
            3,
            0.95),
    EMBEDDED_PREMISES_BKT_AREA_LESS_THAN_100_m2("Встроенные помещения (БКТ), при площади меньше 100 м2",
            "кВт/шт",
            15,
            0.95),
    EMBEDDED_PREMISES_BKT_AREA_MORE_THAN_100_m2("Встроенные помещения (БКТ), при площади больше 100 м2",
            "кВт/м2",
            0.2,
            0.95),
    SS_SPZ_PANEL("Щит СПЗ СС",
            "кВт/шт",
            3,
            0.95),
    GENERAL_EXCHANGE_VENTILATION_SMALL_OBJECTS("Общеобменная вентиляция, небольших объектов",
            "кВт/корпус",
            5,
            0.85),
    GENERAL_EXCHANGE_VENTILATION_NON_HIGH_RISE_BUILDINGS_UP_TO_75_m("Общеобменная вентиляция, не высотных зданий (до 75 м)",
            "кВт/корпус",
            10,
            0.8),
    GENERAL_EXCHANGE_VENTILATION_HIGH_RISE_BUILDINGS_UP_TO_100_m("Общеобменная вентиляция, высотных зданий (до 100 м)",
            "кВт/корпус",
            25,
            0.8),
    GENERAL_EXCHANGE_VENTILATION_UNIQUE_BUILDINGS_UP_TO_200_m("Общеобменная вентиляция, уникальных зданий (до 200 м)",
            "кВт/корпус",
            35,
            0.8),
    ELEVATORS_PP("Лифты ПП",
            "кВт/шт",
            20,
            0.65),
    ELEVATORS("Лифты",
            "кВт/шт",
            20,
            0.65),
    ELECTRIC_THERMAL_CURTAINS_ON_TENAS("Электрические тепловые завесы (на ТЭНах)",
            "кВт/шт",
            10,
            0.98),
    EXTERNAL_LIGHTING_PANEL("Щит наружного освещения",
            "кВт/шт",
            15,
            0.95),
    HEATING_OF_ELECTRIC_PANELS("Отопление электрощитовых",
            "кВт/корпус",
            4,
            0.98),
    PUMPING_STATION_NON_HIGH_RISE_BUILDINGS_UP_TO_75_m("Насосная станция, не высотных зданий (до 75 м)",
            "кВт/шт",
            15,
            0.75),
    PUMPING_STATION_HIGH_RISE_BUILDINGS_UP_TO_100_m("Насосная станция, высотных зданий (до 100 м)",
            "кВт/шт",
            20,
            0.75),
    PUMPING_STATION_UNIQUE_BUILDINGS_UP_TO_200_m("Насосная станция, уникальных зданий (до 200 м)",
            "кВт/шт",
            40,
            0.75),
    WATER_THERMAL_CURTAINS("Водяные тепловые завесы",
            "кВт/шт",
            1,
            0.85),
    LIGHTING("Освещение", "кВт/корпус",
            15,
            0.95),
    ITP_NON_HIGH_RISE_BUILDINGS_UP_TO_75_m("ИТП, не высотных зданий (до 75 м)",
            "кВт/шт",
            10,
            0.75),
    ITP_HIGH_RISE_BUILDINGS_UP_TO_100_m("ИТП, высотных зданий (до 100 м)",
            "кВт/шт",
            20,
            0.75),
    ITP_UNIQUE_BUILDINGS_UP_TO_200_m("ИТП, уникальных зданий (до 200 м)",
            "кВт/шт",
            30,
            0.75),
    PARKING_GATES("Ворота в паркинг",
            "кВт/шт",
            5,
            0.95),
    LIGHTING_PANEL("Щит освещения",
            "кВт/корпус",
            3,
            0.95),
    FACADE_LIGHTING_PANEL("Щит фасадного освещения",
            "кВт/корпус",
            3,
            0.95);

    private final String name;
    private final String units;
    private final double coefficient;
    private final double cos;
}
